language: go
go:
  - "1.22.x"

jobs:
  include:
    - stage: Run and Commit
      if: type = cron
      install: cd src
      script:
        - cd src
        - go run main.go
        - bash .travis-autocommit.sh
