language: go
go:
  - "1.22.x"

jobs:
  include:
    - stage: Run and Commit
      if: type = cron
      before_install:
        - cd src
      install: true
      script:
        - go run main.go
        - bash .travis-autocommit.sh
