name: Run main.go and commit every Friday at 00:00 Tehran time

on:
  schedule:
    - cron: "30 20 * * 4" # 00:00 Friday Tehran time (UTC+3:30)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Run main.go
        run: go run src/main.go

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push
